// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GHQ.Resources.Strings {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GHQ.Resources.Strings.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Error_ApplicationTitle {
            get {
                return ResourceManager.GetString("Error_ApplicationTitle", resourceCulture);
            }
        }
        
        internal static string Error_BackendTitle {
            get {
                return ResourceManager.GetString("Error_BackendTitle", resourceCulture);
            }
        }
        
        internal static string Error_GeneralTitle {
            get {
                return ResourceManager.GetString("Error_GeneralTitle", resourceCulture);
            }
        }
        
        internal static string Error_NoDataFound {
            get {
                return ResourceManager.GetString("Error_NoDataFound", resourceCulture);
            }
        }
        
        internal static string Error_NoInternet {
            get {
                return ResourceManager.GetString("Error_NoInternet", resourceCulture);
            }
        }
        
        internal static string Dialog_Confirm {
            get {
                return ResourceManager.GetString("Dialog_Confirm", resourceCulture);
            }
        }
        
        internal static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        internal static string login_userName {
            get {
                return ResourceManager.GetString("login_userName", resourceCulture);
            }
        }
        
        internal static string login_logInButton {
            get {
                return ResourceManager.GetString("login_logInButton", resourceCulture);
            }
        }
        
        internal static string login_ForgotButton {
            get {
                return ResourceManager.GetString("login_ForgotButton", resourceCulture);
            }
        }
        
        internal static string login_NewAccountButton {
            get {
                return ResourceManager.GetString("login_NewAccountButton", resourceCulture);
            }
        }
        
        internal static string signUp_firstName {
            get {
                return ResourceManager.GetString("signUp_firstName", resourceCulture);
            }
        }
        
        internal static string signUp_middleName {
            get {
                return ResourceManager.GetString("signUp_middleName", resourceCulture);
            }
        }
        
        internal static string signUp_lastName {
            get {
                return ResourceManager.GetString("signUp_lastName", resourceCulture);
            }
        }
        
        internal static string signUp_age {
            get {
                return ResourceManager.GetString("signUp_age", resourceCulture);
            }
        }
        
        internal static string signUp_gender {
            get {
                return ResourceManager.GetString("signUp_gender", resourceCulture);
            }
        }
        
        internal static string signUp_uploadPhotos {
            get {
                return ResourceManager.GetString("signUp_uploadPhotos", resourceCulture);
            }
        }
        
        internal static string signUp_eatingTitle {
            get {
                return ResourceManager.GetString("signUp_eatingTitle", resourceCulture);
            }
        }
        
        internal static string signUp_breakFastTitle {
            get {
                return ResourceManager.GetString("signUp_breakFastTitle", resourceCulture);
            }
        }
        
        internal static string signUp_launchTitle {
            get {
                return ResourceManager.GetString("signUp_launchTitle", resourceCulture);
            }
        }
        
        internal static string signUp_dinnerTitle {
            get {
                return ResourceManager.GetString("signUp_dinnerTitle", resourceCulture);
            }
        }
        
        internal static string signUp_buttonTitle {
            get {
                return ResourceManager.GetString("signUp_buttonTitle", resourceCulture);
            }
        }
        
        internal static string Filter_MedicineName {
            get {
                return ResourceManager.GetString("Filter_MedicineName", resourceCulture);
            }
        }
        
        internal static string Filter_DoctorName {
            get {
                return ResourceManager.GetString("Filter_DoctorName", resourceCulture);
            }
        }
        
        internal static string Filter_DeasesName {
            get {
                return ResourceManager.GetString("Filter_DeasesName", resourceCulture);
            }
        }
        
        internal static string Filter_StartDate {
            get {
                return ResourceManager.GetString("Filter_StartDate", resourceCulture);
            }
        }
        
        internal static string Filter_EndDate {
            get {
                return ResourceManager.GetString("Filter_EndDate", resourceCulture);
            }
        }
        
        internal static string Filter_Button {
            get {
                return ResourceManager.GetString("Filter_Button", resourceCulture);
            }
        }
        
        internal static string Home_newAlarmButton {
            get {
                return ResourceManager.GetString("Home_newAlarmButton", resourceCulture);
            }
        }
        
        internal static string Home_secondButton {
            get {
                return ResourceManager.GetString("Home_secondButton", resourceCulture);
            }
        }
        
        internal static string Home_thirdButton {
            get {
                return ResourceManager.GetString("Home_thirdButton", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_AddVoiceNote {
            get {
                return ResourceManager.GetString("MedicineAddNew_AddVoiceNote", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_AttachImage {
            get {
                return ResourceManager.GetString("MedicineAddNew_AttachImage", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_EditAttachImage {
            get {
                return ResourceManager.GetString("MedicineAddNew_EditAttachImage", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_DailyReminder {
            get {
                return ResourceManager.GetString("MedicineAddNew_DailyReminder", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_EndDate {
            get {
                return ResourceManager.GetString("MedicineAddNew_EndDate", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_Entry_DieseaseName {
            get {
                return ResourceManager.GetString("MedicineAddNew_Entry_DieseaseName", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_Entry_DoctorName {
            get {
                return ResourceManager.GetString("MedicineAddNew_Entry_DoctorName", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_Entry_MedicineName {
            get {
                return ResourceManager.GetString("MedicineAddNew_Entry_MedicineName", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_EventReminder {
            get {
                return ResourceManager.GetString("MedicineAddNew_EventReminder", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_Header_AddComment {
            get {
                return ResourceManager.GetString("MedicineAddNew_Header_AddComment", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_Header_ChooseReminderDate {
            get {
                return ResourceManager.GetString("MedicineAddNew_Header_ChooseReminderDate", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_Header_MedicineInfo {
            get {
                return ResourceManager.GetString("MedicineAddNew_Header_MedicineInfo", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_Header_MedicineReminder {
            get {
                return ResourceManager.GetString("MedicineAddNew_Header_MedicineReminder", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_Header_OtherInfo {
            get {
                return ResourceManager.GetString("MedicineAddNew_Header_OtherInfo", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_MonthlyReminder {
            get {
                return ResourceManager.GetString("MedicineAddNew_MonthlyReminder", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_Picker_ChooseDateTime {
            get {
                return ResourceManager.GetString("MedicineAddNew_Picker_ChooseDateTime", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_Save {
            get {
                return ResourceManager.GetString("MedicineAddNew_Save", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_SaveAndAdd {
            get {
                return ResourceManager.GetString("MedicineAddNew_SaveAndAdd", resourceCulture);
            }
        }
        
        internal static string MedicineAddNew_StartDate {
            get {
                return ResourceManager.GetString("MedicineAddNew_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضغط هنا لتوقيف و تشغيل .
        /// </summary>
        internal static string MedicineAddNew_StopAndPlayVoiceNote {
            get {
                return ResourceManager.GetString("MedicineAddNew_StopAndPlayVoiceNote", resourceCulture);
            }
        }

        internal static string MedicineAddNew_WeeklyReminder {
            get {
                return ResourceManager.GetString("MedicineAddNew_WeeklyReminder", resourceCulture);
            }
        }
        
        internal static string PageHeader_AddNewMedicine {
            get {
                return ResourceManager.GetString("PageHeader_AddNewMedicine", resourceCulture);
            }
        }
        
        internal static string PageHeader_MedicineHistory {
            get {
                return ResourceManager.GetString("PageHeader_MedicineHistory", resourceCulture);
            }
        }
        
        internal static string PageHeader_MedicineSchedule {
            get {
                return ResourceManager.GetString("PageHeader_MedicineSchedule", resourceCulture);
            }
        }
        
        internal static string PageHeader_MedicineSchedule_AllMedicine {
            get {
                return ResourceManager.GetString("PageHeader_MedicineSchedule_AllMedicine", resourceCulture);
            }
        }
        
        internal static string PageHeader_MedicineSchedule_CurrentMedicine {
            get {
                return ResourceManager.GetString("PageHeader_MedicineSchedule_CurrentMedicine", resourceCulture);
            }
        }
        
        internal static string PageHeader_UpdateNewMedicine {
            get {
                return ResourceManager.GetString("PageHeader_UpdateNewMedicine", resourceCulture);
            }
        }
        
        internal static string SignUp_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUp_ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string SignUP_BreakFast {
            get {
                return ResourceManager.GetString("SignUP_BreakFast", resourceCulture);
            }
        }
        
        internal static string SignUP_launch {
            get {
                return ResourceManager.GetString("SignUP_launch", resourceCulture);
            }
        }
        
        internal static string SignUP_Dinner {
            get {
                return ResourceManager.GetString("SignUP_Dinner", resourceCulture);
            }
        }
    }
}
